import { ApiProperty } from '@nestjs/swagger';

/**
 * A single room-level report generated by the AI when the session ends. It
 * reflects the whole group's talk (not per-participant), summarising how the
 * conversation went and how to improve next time.
 *
 * Declared as a class so `@nestjs/swagger` can reflect it; object literals stay
 * structurally assignable.
 */
export class RoomReport {
  @ApiProperty({
    description: 'A few-sentence summary of how the session went.',
    example:
      'A lively 20-minute session that started on weekend plans and branched into travel, food and personal goals. The group sustained the conversation well and adapted to two topic pivots.',
  })
  summary!: string;

  @ApiProperty({
    type: [String],
    description:
      'Positive highlights — strong moments, good vocabulary, effective turn-taking.',
    example: [
      'Rich travel vocabulary: "off the beaten track", "a hidden gem".',
      'Good use of follow-up questions to keep quieter speakers involved.',
    ],
  })
  highlights!: string[];

  @ApiProperty({
    type: [String],
    description: 'Actionable suggestions for the group to improve next time.',
    example: [
      'Practise past-tense narration — several stories slipped into the present.',
      'Try paraphrasing when stuck instead of switching to single words.',
    ],
  })
  suggestions!: string[];

  @ApiProperty({
    type: [String],
    description: 'Distinct topics the conversation actually explored.',
    example: ['weekend plans', 'coastal travel', 'street food', 'personal goals'],
  })
  topicsExplored!: string[];

  @ApiProperty({
    format: 'date-time',
    description: 'When the report was generated (ISO-8601).',
    example: '2026-07-12T18:45:03.000Z',
  })
  generatedAt!: string;
}
